version: '2'
services:
 jekyll:
    image: jekyll/jekyll:pages
    container_name: me2nardo
    command: jekyll serve --watch --incremental
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
